### ISSUE TITLE
Thematic maps dialogues - bug

### ISSUE THREAD

**Issue by SannaJokela** [oskariorg/oskari-docs#100]
Is this a functionality or a bug: when clicking a thematic map pop-up window the time series tool and legend stay behind - only way to get rid of them is through selected layers and removing the thematic layer. The system could say: "Do you want to close the selected thematic map also" when clicking the thematic map tool away.

![ptikkuna_bugi](https://user-images.githubusercontent.com/23258285/54532136-bbb71680-498f-11e9-825e-e1f3dcab9818.PNG)

Another similar example - the thematic map layer has been closed, but you can still click the diagram but it does not show any layers: 

![ptikkuna_bugi2](https://user-images.githubusercontent.com/23258285/54532466-7c3cfa00-4990-11e9-9ade-987b2a913889.PNG)

**Comment by ZakarFin** [comment]
Even though the diagram can be opened it says that there's no data to show so I don't think it's a bug :) How should it work in your opinion? I think it's better to show there's such an option than hide everything but the search when the user hasn't selected anything yet. Thought the search window could open automatically in this case to reduce the number of clicks the user can make.

Also asking the user if he/she would like to remove the thematic map when exiting the functionality is a matter of opinion. Clicking the thematic map tile is an easy way to close all the windows on top of the map for the user to see the thematic map. Do we want to burden the user with asking if the layer should be removed? I guess it's kind of the same if the user exits the analysis functionality. Should we ask the user if all analysis layers should be removed from the map?

**Comment by SannaJokela** [comment]
The first example: there could be a button to close those time series and legend windows also. Because now I did not even realize first that the thematic map layer was still "in action". I think this functionality is a bit misleading and should be revised. I'll check all the similar cases and Joint Developmen Forum could check the possibilites in the UI development so that this could be corrected in the future.

**Comment by tmiosmauli** [comment]
The behavior of the thematic maps "tile" will be changed to the next version (1.56) as follows:
- the tile will close (hiding the extra buttons for bar chart etc) when another one is opened
- opened UI-elements related to the thematic map (legend, time series control, etc) will not be closed (as they are needed to interpret the thematic map still visible)
- however the "Search data"-flyout will be closed as it shouldn't be needed and takes a lot of screen-space
- independently of the tile the other thematic map related UI-elements will be closed when there is no longer any indicator data to show (there's no point showing them empty)

As mentioned, these changes will be included in the next release (1.56.) and this issue can be closed.

**Comment by ZakarFin** [comment]
Changes are included in the 1.56.0 release. Closing the issue
