### ISSUE TITLE
Thematic maps dialogue shows that there is no indicators - still shows the indicator

### ISSUE THREAD

**Issue by SannaJokela** [oskariorg/oskari-docs#101]
When adding an indicator to Thematic maps - the service says sometimes that there is no indicators available (this is quite frustrating - why the data is shown then?) but in this case, the indicator was there but still an error occurred... Is it a bug or data related issue?

![ptikkuna_bugi1_2](https://user-images.githubusercontent.com/23258285/54532357-40099980-4990-11e9-8622-ae93da51ac50.PNG)

**Comment by ZakarFin** [comment]
You tried to fetch data from 1987-2017 and the popup says that there's only data for 2008-2017. For this particular datasource we don't get indicator specific ranges for the time variable so we need to show the user the years that the datasource declares it has for all it's indicators even if it doesn't have the data for all the years for all the indicators. Of course we could prefetch all the data from a given datasource and process it daily or something to detect if the datasource actually has the data it says it has, but we do not.

Other APIs like the SotkaNET one actually tells year ranges/indicator so we can show only the matching ones. Even then there might be errors in the metadata depending on the indicator or the datasource.

**Comment by ZakarFin** [comment]
We could clarify the message from "didn't get data" -> "didn't get _all_ the data" though :)

**Comment by SannaJokela** [comment]
Ok, I understand and your suggestion about the message would help - because current message is confusing.
