### ISSUE TITLE
Data provider list not correctly refreshed when a new item is added

### ISSUE THREAD

**Issue by blackfolder** [oskariorg/oskari-docs#103]
Let's consider scenario:

![form](https://user-images.githubusercontent.com/32539683/54691059-ebe2ee80-4b22-11e9-9f2a-6cfe31e33914.png)

A new map layer is added or existing map layer is edited using the admin-hierarchical-layerlist bundle. A new data provider ("Tiedontuottaja") is added, saved, automatically selected for that map layer and the map layer add/edit form is saved. The newly added data provider is correctly saved for that map layer. But the newly added data provider exists on the data providers dropdown list only until the form is closed. When we we open the popup edit form for the same map layer, then this newly added data provider doesn't exist on the list and cannot be correctly selected for the map layer. This is beacuse the data provider list is not refreshed (it is "cached" - once loaded it is not refreshed, see: 'Oskari.admin.hierarchical-layerlist.Layer'). To have a newly added data provider be visible on the list and correctly selected for the layer, we have to refresh the application. 

To solve that problem I'd suggest let the getDataproviders method in the 'Oskari.admin.hierarchical-layerlist.Layer' get data from server every time the form popup is open or refresh the the data providers list when a new data provider is added using request.

**Comment by ZakarFin** [comment]
Thanks for reporting this. I guess it's not that common to add data providers after some initial setup so this issue hasn't been detected before. We are currently rewriting the layer admin functionality as a whole so I'm not sure the current one will receive much love for now.

**Comment by blackfolder** [comment]
Thank you for the answer. I did a fix we needed for a current version of admin-hierarchical-layerlist bundle.

**Comment by ZakarFin** [comment]
The new layerlist bundle has been included in 1.55.x and it updates properly on data provider changes. Closing the issue since there hasn't been a any activity regarding the hierarchical layerlist or this issue.
