### ISSUE TITLE
Hierarchical layerselector list not refreshed after main group deleted

### ISSUE THREAD

**Issue by blackfolder** [oskariorg/oskari-docs#104]
When a main group is deleted from hierarchical layerselector using admin tools, then the list is not refreshed beacuse an exception is thrown in 'Oskari.mapframework.service.MapLayerService' in deleteLayerGroup. For the main group parentId = -1 and getAllLayerGroups method in MapLayerService returns null in that case. See:

![screenshot](https://user-images.githubusercontent.com/32539683/55003221-44f5cb00-4fd8-11e9-91c8-ce9d601ee640.png)

The line that causes this problem is 
            return (id) ? layerGroups : this._layerGroups; in getAllLayerGroups method
It should be changed to 
             return (id && id !== -1) ? layerGroups : this._layerGroups;
shouldn't it?

If my fix is correct than I can submit a pull request for that.

**Comment by ZakarFin** [comment]
Sure, please do!

**Comment by ZakarFin** [comment]
Fix merged and will be included in 1.52.0
