### ISSUE TITLE
Layer not removed from the group in hierarchical layerlist

### ISSUE THREAD

**Issue by blackfolder** [oskariorg/oskari-docs#105]
When user changes the layer group assignment using 'Valitse ryhmät' button in the layer edit form in the following way:
assigns layer to a new group or groups and REMOVES that layer from the group it currently belongs to, then the layerselector list is not correctly refreshed (the moved layer is still visible in the group that it was removed from). After refresing the browser everything works fine.

![example](https://user-images.githubusercontent.com/32539683/56034704-62d96480-5d28-11e9-9e6d-c41d889a793b.png)

![example2](https://user-images.githubusercontent.com/32539683/56034785-a6cc6980-5d28-11e9-9e13-beb2e8849e83.png)

Refresh doesn't work, beacuse the updateLayersInGroups method in 'Oskari.mapframework.service.MapLayerService' doesn't takie into account layer update (only delete and add options).

Fix for that in the pull request #855

**Comment by ZakarFin** [comment]
Fix merged and will be included in 1.52.0
