### ISSUE TITLE
Styles selection dropdown not initialized correctly

### ISSUE THREAD

**Issue by blackfolder** [oskariorg/oskari-docs#106]
The styles dropdown selection is automatically shown if layer has more than one style to be chosen.  If not, it's shown when a custom style is saved for that layer.
But in case if the dropdown wasn't initialized at the begining when a map layer was selected, then, when a custom style is added me._binded property is already set to true and code:

sel.on('change', function (e) {
                var val = sel.find('option:selected').val();
                me._layer.selectStyle(val);
                me.sb.postRequestByName('ChangeMapLayerStyleRequest', [me._layer.getId(), val]);
            });

is not executed. Because of that layer style is not updated after reselecting in the dropdown list.

![styles](https://user-images.githubusercontent.com/32539683/56035908-bbf6c780-5d2b-11e9-9408-e61ebc274615.png)

Fix in the pull request #856 .

**Comment by ZakarFin** [comment]
Fix merged and will be included in 1.52.0
