### ISSUE TITLE
WFS 2.0.0 questions

### ISSUE THREAD

**Issue by blackfolder** [oskariorg/oskari-docs#107]
I have questions related to WFS 2.0.0 (oskari-feature-engine) layers.

*** 1. In Liiteri app we needed some support for feature params customization and I basically implemented there what we needed. But..

While working on that task I found some commented out code in the FEOutputProcessor.java line 160:

         List<String> layerSelectedProperties = layer
         .getSelectedFeatureParams(session.getLanguage());
         
Does it mean that there's a plan to continue with that? I mean: will there be any control of properties that should be visible in the popup implemented in the future?

*** 2. Now for the WFS 2.0.0 layers the gml_geometry_name in the portti_wfs_layers table is set to "geometry" by default. In case of layers that we use the gml_geometry_name  may vary depending on the layer. I tried to find in the code an already existing way to handle that problem but I didn't succeed. Am I missing something?

**Comment by ZakarFin** [comment]
Hi and sorry for the delay.

1) We have been implementing a new backend for the WFS-integrations and as such there are no plans for continuing work with the transport-backend. The next version of Oskari will have an initial version of the new backend that you can start testing with but it doesn't support WFS 2.0 yet. Testing the new backend requires configuration changes which we will provide in the migration guide as optional migration step. The transport backend will still the default one for the next version.

2) The portti_wfs_layers table is populated when a WFS-layer is registered to the Oskari instance with the layer administration functionality (admin-layerselector bundle). The geometry field as well as the others are populated by the result of DescribeFeatureType request done to the service by the admin UI.

**Comment by blackfolder** [comment]
Thanks a lot for your answers!

**Comment by ZakarFin** [comment]
In 1.55 the wfs-specific toggles and configurations are migrated to oskari_maplayer.attributes (oskariorg/oskari-server#509). Closing this old question as I don't think it helps anyone anymore.
