### ISSUE TITLE
WFS / featuredata2 guest role download permission handling

### ISSUE THREAD

**Issue by kuosman** [oskariorg/oskari-docs#108]
Now guest role user(s) cannot export WFS data even though the download right is given to wanted WFS-layer.

Permission handling need to change so at also guest role download permission allows guest users export WFS layer(s).

**Comment by ZakarFin** [comment]
Makes sense. You would need to copy the permission check from a few lines below here https://github.com/oskariorg/oskari-server/blob/1.51.1/service-map/src/main/java/fi/mml/map/mapwindow/util/OskariLayerWorker.java#L272

**Comment by ZakarFin** [comment]
Guest users can have download permission for enabling download for the featuredata at least on 1.55.x but probably even on an earlier version
