### ISSUE TITLE
Preconditions for saving drawn map figures

### ISSUE THREAD

**Issue by Miselius** [oskariorg/oskari-docs#11]
AH-3565
Issue with preconditions for saving drawn map figures

Line Tool:
-The precondition for saving a drawn Line figure should be 2 points or finished figure (double click)
->Currently can be saved with 1 point (form opens)

Area Tool:
-The precondition for saving a drawn Area figure should be 3 points or finished figure (double click)
->Currently can be saved with 1 point (form doesn't open)

**Comment by ZakarFin** [comment]
Fix included in 1.44.0
