### ISSUE TITLE
GetUserLocationRequest or/and mylocation bundle error

### ISSUE THREAD

**Issue by kuosman** [oskariorg/oskari-docs#113]
GetUserLocationRequest or mylocation plugin not handle case when you first call request and then try to locate your location, says timeout...

Steps:
* go: https://kartta.paikkatietoikkuna.fi/
* run: Oskari.getSandbox().postRequestByName('StartUserLocationTrackingRequest', [{addToMap: 'location', centerMap: 'single'}]);
* try to click mylocation plugin, then says: 'Paikannuksessa kestää odotettua kauemmin..." 

Also missing en locales (fi has more than en):
* https://github.com/oskariorg/oskari-frontend/blob/master/bundles/mapping/mapmodule/resources/locale/fi.js#L115

**Comment by ZakarFin** [comment]
Fixed in oskariorg/oskari-frontend#979
