### ISSUE TITLE
Bug - feature info with arcgis wfs services

### ISSUE THREAD

**Issue by MinnaRy** [oskariorg/oskari-docs#114]
Bug report: When one adds a wfs 2.0.0 (published at ArcGis Server) to Oskari, Oskari doesn't show feature information, not with a mouse clic nor by the Feature Data button. If the service is brought as wfs 1.1.0 it doesn't work at all or the problem is the same. If wfs version definition is changed AFTERWARDS to 1.1.0, information is shown BUT in wrong order ie. data values are shown under wrong field titles. 
I have Oskari 1.44, but I can see that there might be the same thing in Paikkatietoikkuna (see for example GTK:s Kallioperä wfs). I have tested several arcgis services and this seems to happen with all wfs 2.0.0 services no matter which organisation has published them.

**Comment by ZakarFin** [comment]
Thanks for letting us know! We'll take a look at it.

**Comment by ZakarFin** [comment]
Tested this on kartta.paikkatietoikkuna.fi using Kallioperä 1:1 000 000 and I'm getting the feature info with clicking and on the feature data table. Its not pretty but it is there. Either this has been fixed while working on the WFS integrations or there was some temporary problem with the service at the time of initial testing
