### ISSUE TITLE
Removing data provider impossible

### ISSUE THREAD

**Issue by blackfolder** [oskariorg/oskari-docs#118]
Hi,

Now it's impossible to remove data provider (Tiedontuottaja) from dropdown list in layer add/edit admin form. I know that layer admin functionality (see answer for issue: https://github.com/oskariorg/oskari-docs/issues/103) is going to be rewritten. So I have two questions:
- When can we expect new admin-hierarchical-layerlist bundle?
- Is it going to be possible to remove data provider in the new version?

**Comment by ZakarFin** [comment]
Removing a data provider works on the "classic" admin so this looks like a hierarchical-layer-admin issue only. 

The target for releasing the new layer admin later this year. It has been on hold for a while with the new WFS integration changes being more urgent but we are continuing the development in the near future. The new layer admin won't probably work out of the box with the hierarchical-layerlist bundle but will need some modifications. The current development for the new React based layer listing can be found/followed here: https://github.com/oskariorg/oskari-frontend/tree/develop/bundles/framework/layerlist and the new admin functionality in here https://github.com/oskariorg/oskari-frontend/tree/master/bundles/admin/admin-layereditor (+ https://github.com/oskariorg/oskari-frontend/pull/829)

**Comment by ZakarFin** [comment]
There hasn't been any activity regarding this for almost a year and we now have the new admin that we recommend to be used.
