### ISSUE TITLE
Allow modifying legend url on the admin UI

### ISSUE THREAD

**Issue by ernoma** [oskariorg/oskari-docs#119]
As discussed in [Oskari Gitter](https://gitter.im/oskariorg/chat?at=5d22db6126a152537e47791f) by Jarno Kinnunen and Sami Mäkinen it would be useful to customize the GetLegendGraphic call to the WMS server via the Oskari admin UI.

**Comment by ZakarFin** [comment]
We could change the logic so that if a legend url is given manually by the admin it is always shown as the legend for the layer. Now it's more of a fallback when capabilities doesn't include a legend url.

**Comment by ZakarFin** [comment]
If the override is done, would it be shown for each style the layer has? Or if the layer has multiple styles should the admin be allowed to override the legend url for each style?

**Comment by ernoma** [comment]
I cannot say much of the need in this specific 119 issue, so I sent email to Jarno Kinnunen if he wants to comment on this. However, regarding the #120 I can describe the use case, so I added my comment there.

**Comment by ZakarFin** [comment]
In 2.2.0 the legend handling was improved on the React-based admin. The admin can define overriding urls per style for legends. This should solve this issue.
