### ISSUE TITLE
Drawn figures are left on the map after closing the save-form by icon

### ISSUE THREAD

**Issue by Miselius** [oskariorg/oskari-docs#12]
AH-3564
In Oskari maps which allow user to draw and save figures on the map layer (line/area tool), there is an issue with closing the save-form by the icon.

The buttons "Cancel" and "Save" work as intended but the closing X-icon in the top corner of the form window currently only closes the form, which causes the drawn figure to remain on the map.

The icon should be removed or linked to "cancel" functionality.

**Comment by ZakarFin** [comment]
Fixed included in 1.44.0
