### ISSUE TITLE
Allow specifying default map legend on the admin UI even if one is available from the WMS server

### ISSUE THREAD

**Issue by ernoma** [oskariorg/oskari-docs#120]
Related to #119 it would also be useful if the map legend graphic could be overriden via the admin UI even if legend graphic is available from the WMS server.

**Comment by ernoma** [comment]
We have a graphic artist employed in the planned land use unit and we publish map layers that include, for example, legends that the graphic artist has worked on. Two examples:
- https://kartat.tampere.fi/oskari/action?action_route=GetLayerTile&legend=true&id=2891
- https://kartat.tampere.fi/oskari/action?action_route=GetLayerTile&legend=true&id=2448

However, if we try to specify the legends via GeoServer then they are not properly shown in the Oskari Map Legends tab. If they are specified via the Oskari UI then they show up fine in the Map Legends tab, but we can only specify them via the Oskari UI when we are providing a layer group from GeoServer. 

So, that we would not need to create a "dummy" layer group in the GeoServer just to be able to specify the image URL in Oskari it would be useful to be able to specify the image URL also for single layers even though they have the default legend provided by the GeoServer (that does not work with Oskari in our use case).

**Comment by ZakarFin** [comment]
In 2.2.0 the legend handling was improved on the React-based admin. The admin can define overriding urls per style for legends. This should solve this issue.
