### ISSUE TITLE
Thematic maps bar chart window scroll bar issue

### ISSUE THREAD

**Issue by mr-lev1** [oskariorg/oskari-docs#155]
Hello,

I noticed a small bug with the bar chart window of the thematic maps feature. If you select multiple indicators for a thematic map and try to change the shown indicator in the bar chart window, the scroll bar disappears and the data overflows outside the window.

**Before changing indicator:**
![bar_chart_working](https://user-images.githubusercontent.com/18393492/71899938-7570b500-3165-11ea-96a3-edb645f549a4.PNG)

**After changing indicator:**
![bar_chart_broken](https://user-images.githubusercontent.com/18393492/71899989-8de0cf80-3165-11ea-82c9-7603e4b8aae9.PNG)

This problem can be repeated e.g. in https://kartta.paikkatietoikkuna.fi/.

**Comment by ZakarFin** [comment]
Thanks for letting us know!

**Comment by ZakarFin** [comment]
This was fixed in oskariorg/oskari-frontend#1226 and will be included in the upcoming 1.55.0 release.
