### ISSUE TITLE
Info buttons on layer selection moves one step upwards

### ISSUE THREAD

**Issue by jussitah** [oskariorg/oskari-docs#156]
-	Layer menus availability, additional information and map layer type buttons moves one step upwards from map layer section.
-	Happens when you use Firefox web browser (Google chrome works fine)
![oskari_1](https://user-images.githubusercontent.com/34504166/72134232-248ed580-338c-11ea-9a65-4e74bf74ae78.png)

**Comment by ZakarFin** [comment]
Looks like this is the hierarchical-layerlist bundle. Can't be reproduced on the old layerselector2 or the new layerlist bundles.

Ping @kuosman to check this.

**Comment by ZakarFin** [comment]
Fixed in https://github.com/oskariorg/oskari-frontend/pull/1196
