### ISSUE TITLE
Infobox re-opens when you switch it off

### ISSUE THREAD

**Issue by jussitah** [oskariorg/oskari-docs#157]
-	When you close info window Oskari re-opens new info window if there is map layer and a feature behind info window close button.
-	Happens when you use Firefox web browser (Google chrome works fine)
![oskari_2](https://user-images.githubusercontent.com/34504166/72134480-e645e600-338c-11ea-8a85-0c33e1b5ad7c.png)
![oskari_3](https://user-images.githubusercontent.com/34504166/72134486-e9d96d00-338c-11ea-975d-124585950cbb.png)

**Comment by ZakarFin** [comment]
True, seems to work on chrome and IE but not on Firefox. This should fix it: oskariorg/oskari-frontend#1118 but I'm not sure if we are going to hotfix it or will it stick around for the next release (current plans are for February release)

**Comment by ZakarFin** [comment]
Fixed on oskariorg/oskari-frontend#1118
