### ISSUE TITLE
Open map services with HTTPS support should not be proxied by default

### ISSUE THREAD

**Issue by tsallinen** [oskariorg/oskari-docs#19]
To improve performance and scalability, open WMS/WMTS/ArcGIS-layers should not be unnecessarily proxied through Oskari Server. Currently layers are always proxied if SSL/TLS (HTTPS) is enabled in Oskari instance. To allow direct access to HTTPS enabled map services from the frontend should proxying be disabled if all of the following conditions are met:

- layer url starts with https://
- layer doesn't have authentication configured
- forceProxy attribute is not set or is false for the layer

This has already been implemented and a pull request is being prepared by NLSFI.

**Comment by ZakarFin** [comment]
This should fix the issue: https://github.com/nls-oskari/oskari-server/commit/645896dea2a03a741784834bc39d43785283f798. The secure prefix was also a problem for URLs that point back to oskari-server like with "my places" layers (urls like "/action").

**Comment by ZakarFin** [comment]
Seems to work ok for layer tiles, but there's still an issue with map layer legend images loaded using HTTP instead of HTTPS.

**Comment by ZakarFin** [comment]
This has been implemented.
