### ISSUE TITLE
Broken admin UI when multiple locales are set

### ISSUE THREAD

**Issue by senoadiw** [oskariorg/oskari-docs#195]
Oskari version: 1.55.2

My oskari.locales=id_ID,en_US,fi_FI,sv_SE,es_ES. Editing a theme name in the new map layer menu shows a broken UI for the add/edit theme window. There is no issue when saving/editing a value for a language.

Screenshot:
![image](https://user-images.githubusercontent.com/1198399/80959146-63abcf80-8e30-11ea-9f71-f3ccd441ed20.png)

**Comment by ZakarFin** [comment]
Fix included in 2.0
