### ISSUE TITLE
List of core contributor organisations

### ISSUE THREAD

**Issue by SannaJokela** [oskariorg/oskari-docs#208]
We have list of organisations in community pages but, we could add a list of core companies that have the ability to develop Oskari. At least this issue is usually asked from me. Would this be ok?

Suggestion:
Place for core contributor list under oskari.org/community ==> corecontributors.md

Questions:
1. How to get on the list?

**Comment by ZakarFin** [comment]
I wouldn't name it "code contributors". You can get such lists from Github:
- https://github.com/oskariorg/oskari-frontend/graphs/contributors
- https://github.com/oskariorg/oskari-server/graphs/contributors

Maybe just call it a list companies that are offering development effort for Oskari based apps?

**Comment by SannaJokela** [comment]
Yes, I'll make a suggestion of the page. Now on my "secret" list are following companies, some of them are not community members, so they do not have information in the organisation page:

Sitowise
Hubble
Ubigu
Gispo
CGI
Cybercom
Siili
PHZ Consulting

**Comment by ZakarFin** [comment]
I guess this can be closed since #213 is merged?
