### ISSUE TITLE
WCS-service support

### ISSUE THREAD

**Issue by ZakarFin** [oskariorg/oskari-docs#21]
Initial support for Web Coverage Services in Oskari: http://www.opengeospatial.org/standards/wcs

Responsible party: NLS Finland. Schedule Q3-Q4/2017

**Comment by ZakarFin** [comment]
Service for making WCS requests and reading responses in oskariorg/oskari-server#89 - a sample for using this to generate height profile will be included in https://github.com/nls-oskari/kartta.paikkatietoikkuna.fi later this year.

**Comment by jampukka** [comment]
A module using Oskari WCS module:
https://github.com/nls-oskari/kartta.paikkatietoikkuna.fi/tree/develop/service-terrain-profile

**Comment by ZakarFin** [comment]
Initial version has been implemented so this roadmap item is completed.
