### ISSUE TITLE
Oskari blog titles and images visible at landing page

### ISSUE THREAD

**Issue by SannaJokela** [oskariorg/oskari-docs#215]
Communication team suggested that it would be good to have a section at oskari.org landing page that shows for example the 3 latest blogs with title text, image and description. This probably could be done by the same method as the gallery page?

**Comment by ZakarFin** [comment]
If this is the case we might actually want to implement the blog functionality on oskari.org rather than have the blog under separate repository and address

**Comment by ZakarFin** [comment]
Solved in the new site: https://github.com/oskariorg/oskari-documentation-site/ (once it's ready to be published :)) Latest blogs are listed on the landing page on that one and we'll remove the blogs from oskariorg.github.io once we launch the new one.
