### ISSUE TITLE
Add new settings for Cesium 3D Tiles layers

### ISSUE THREAD

**Issue by mr-lev1** [oskariorg/oskari-docs#235]
There is a need for setting some additional values related to the Cesium 3D Tiles layers. These settings should be configurable as separate fields in the Layer administration -tool (Visualization-tab). If set, the values would then be added to an options-object and stored to the database.

The options needed are:
1. dynamicScreenSpaceError
2. dynamicScreenSpaceErrorDensity
3. dynamicScreenSpaceErrorFactor
4. dynamicScreenSpaceErrorHeightFalloff

Currently these values have [default values in Oskari](https://github.com/oskariorg/oskari-frontend/blob/e8ea1f80fc5cd620ad28ab984556dd44104967e7/bundles/mapping/tiles3d/plugin/Tiles3DLayerPlugin.js#L195-L198) and they should only be overridden if the user modifies these default values in layer settings.

### Development project goals:
- Implement fields for the settings in the Visualization-tab of the Layer administration (only show them when adding a 3D layer)
- Implement tooltips for the fields that guide the user towards making good decisions ([check this for reference](https://cesium.com/docs/cesiumjs-ref-doc/Cesium3DTileset.html))
- Implement storing the setting to the database in an options-object (store only if modified)

**Comment by ZakarFin** [comment]
Sounds good. Though I could see these as being mostly visualization toggles for 3D so they could be on that tab instead of "Additional"-tab

**Comment by mr-lev1** [comment]
Thanks, good point! Modified the issue description regarding the tab.

**Comment by ZakarFin** [comment]
The implementation was merged to develop and it will be included in the 2.2.0 release.
