### ISSUE TITLE
Audit log of read access

### ISSUE THREAD

**Issue by jampukka** [oskariorg/oskari-docs#243]
Currently there's no way to produce an audit log of read access to layers with non-public or sensitive information. As the requirements and use cases may vary between different services and or instances of Oskari I suggest we add a mechanism to oskari-server that server-extensions can then hook into. It is safe to assume such layers to be configured with username and password set so all access to them gets proxied through oskari-server. The described functionality should add minimal overhead to instances of Oskari that don't need it.

In addition we probably need to "warn" the user before opening (enabling) such a layer so that user understands that the action will be logged, but this can probably be done totally on frontend extensions.

**Comment by ZakarFin** [comment]
Sounds good to me

**Comment by ZakarFin** [comment]
Initial hook enabler added in 2.2.0
