### ISSUE TITLE
Add support for importing GeoPackages

### ISSUE THREAD

**Issue by jampukka** [oskariorg/oskari-docs#246]
It would be nice if one could import GeoPackages into Oskari via `CreateUserLayer` ActionRoute.

For first version it would be sufficient for the implementation to pick the first entry from `gpkg_contents` table with `data_type` of  `features` which is non-empty (e.g. the referenced table has rows). This would be similar to the way we pick the first non-empty layer from GPX files following Tracks > Routes > Waypoints.

**Comment by ZakarFin** [comment]
Merged server-side changes for 2.3.0

**Comment by ZakarFin** [comment]
Frontend localization added in https://github.com/oskariorg/oskari-frontend/pull/2122 so we can finally close this :)
