### ISSUE TITLE
MID/MIF import fails

### ISSUE THREAD

**Issue by summamutikka** [oskariorg/oskari-docs#250]
MID/MIF import to Oskari fails, not sure what is the problem. 
Tested in several latest Oskari instances. 

Error message: 
![image](https://user-images.githubusercontent.com/31657333/121142376-977fd280-c844-11eb-9d5d-5ca28e9d6c94.png)

According to the user, this format was valid ca. one year ago: 

_Version   750
Charset "WindowsLatin1"
Delimiter ","
CoordSys Earth Projection 2008, 115, "m", 27, 0, 0.9996, 500000, 0 Bounds (-100000, 6000000) (1000000, 8000000)
Columns 1
  Koeala Char(200)
Data
Region 1
4
354900.6 6860211.1
354935.3 6860181.5
354961.1 6860199.3
354918.9 6860237.3_

**Comment by jampukka** [comment]
I'll look at it tomorrow

**Comment by ZakarFin** [comment]
Did this solve it https://github.com/oskariorg/oskari-server/pull/735?

**Comment by summamutikka** [comment]
Tested with the original data: importing mid/mif works. Thanks @jampukka ! :)
