### ISSUE TITLE
Layerlist flyout width clips content on Firefox

### ISSUE THREAD

**Issue by WTurunen** [oskariorg/oskari-docs#251]
When using Firefox, the layerlist flyout width doesn't adjust properly to its content. Instead it can hide important information from the layer list e.g. the layer tools. 

![image](https://user-images.githubusercontent.com/3134372/130015577-9155e220-0639-43e9-8428-1e006adaad3f.png)

The width problem varies according to the layer list content. 

![ff1](https://user-images.githubusercontent.com/3134372/130017260-8f80c067-a434-4b0a-8c46-6eeab271abc4.gif)
![ff2](https://user-images.githubusercontent.com/3134372/130017273-6aa6b56d-b670-4531-8869-5628e5a92f78.gif)

On Chrome and Edge it works like it should.

## Expected Behavior
The flyout width adjusts to its content looking good and hiding nothing.

## Actual Behavior
The width doesn't adjust and hides some information e.g. the layer tools.

## Possible Fix
A quick fix would be to set `overflow: visible` to `.ant-tabs`, but that cuts to the padding and looks bad. 

## Steps to Reproduce
1. Using Firefox, visit a relatively new Oskari-installation e.g. https://kartta.paikkatietoikkuna.fi
2. Open map layers menu item

## Context
This bug may hide layer tools from users so that the may not see the layer metadata. It also looks bad.

## Your Environment
* Oskari front-end version: 2.4.0
* Browser Name and version: Firefox 91.0.1
* Operating System and version: Windows 10, 1902

**Comment by ZakarFin** [comment]
Thanks for the detailed report!

**Comment by ZakarFin** [comment]
Just merged a fix for this for the next version (2.5). Current plans for release schedule is early October.
