### ISSUE TITLE
'Show map legend' -tool in Map publishing does not work

### ISSUE THREAD

**Issue by mr-lev1** [oskariorg/oskari-docs#252]
'Show map legend' -tool in Map publishing currently seems to work only while creating a new embedded map in the editor. Also, it seems to disappear from the editor after creating or modifying an embedded map:

![oskari_map_publish_legend_tool_bug](https://user-images.githubusercontent.com/18393492/131826641-ccc15a71-6c52-4988-87a8-d09470838411.gif)

In the published view the legend does not seem to show up at all:

![oskari_map_publish_legend_tool_bug](https://user-images.githubusercontent.com/18393492/131827711-b8318717-8735-4631-a38c-5ae7de3d0893.PNG)

Tested with the latest demo.oskari.org -version.

**Comment by mr-lev1** [comment]
Sure, no problem! I can try to debug/fix this before the next release.

**Comment by ZakarFin** [comment]
Fixes merged so this should be fixed for the next version 2.6.0 (with tentative release date of mid January 2022).
