### ISSUE TITLE
Add a cookie warning/consent popup to Oskari

### ISSUE THREAD

**Issue by mr-lev1** [oskariorg/oskari-docs#253]
It would be nice to have a possibility to add a cookie warning/consent popup to Oskari. This kind of warning is not always needed as the GDPR clearly states that a consent from the user for using cookies is only needed when the service uses cookies that are not mandatory for the service to store in order for it to function properly. But for some implementations using Oskari it would be a useful addition since other additional cookies might be in use.

The content of this "cookie popup" should be easily configurable in _oskari-ext.properties_ and/or with a template that defines the content.

**Comment by rekjuh** [comment]
@mr-lev1 is this still something you wish the Oskari team would work on? We're moving all the issues to Oskari-documentation repo. If you wish to keep this open and get updates, please create a new issue here: https://github.com/oskariorg/oskari-documentation/issues

**Comment by mr-lev1** [comment]
@rekjuh To be honest, I haven't had a chance (sadly) to use Oskari in a while due to switching to another employer back in 2022. I think this request was related to a project I was working on back in 2021. 

Still a nice feature, though. But not mandatory for me currently.
