### ISSUE TITLE
WMS GFI not handle correctly cases when using different style than default

### ISSUE THREAD

**Issue by kuosman** [oskariorg/oskari-docs#261]
When using different WMS style than default also hidden features (not visible in current style) can be seen on GFI.

Problem is in `oskari-frontend` (not send WMS styles to server) and `oskari-server` need also modifying so at GFI request include also selected WMS style.

For example in Suomen Väylät is Road bridges WMS map layer that normally shows all road bridges but map layer has also weight-restricted bridges style and when using this style we get also GFI responses for unvisible bridges (all bridges).   

![wms-gfi-error](https://user-images.githubusercontent.com/570159/145546335-ed996069-7757-447c-949e-e0e6f0845ae9.gif)

**Comment by ZakarFin** [comment]
Thanks for reporting this! So the frontend doesn't send the currently selected style per layer on GFI-requests and/or server doesn't pass the style in the request to the actual service.

**Comment by ZakarFin** [comment]
Fixes merged in develop branch for Oskari 2.6 (due mid-January). Thanks @kuosman!
