### ISSUE TITLE
Layer count not working correctly in layer tree

### ISSUE THREAD

**Issue by Koivusto** [oskariorg/oskari-docs#268]
There is a possible bug in the way layers in groups are counted in Oskari front end. Layer count stops working for uppermost groups that comprise of several subgroups under which actual map layers reside. The behavior has been witnessed in web map of city of Tampere where a common end user can see it happening without logging in. Please see the image attached. The web map service can be found [here](https://kartat.tampere.fi/oskari/).

Not sure if the count in upper group layer should comprise of actual map layers in any subgroup or of number of subgroups. Used versions are 2.5.1 in frontend and 2.5.3 in server.

![layer_count_bug_in_layer_tree](https://user-images.githubusercontent.com/24698263/152770380-7cd945e8-9b24-40a0-a164-44d816a16985.png)

**Comment by ZakarFin** [comment]
Thanks for reporting though this is a known issue. The layer counter wasn't updated when the hierarchy support was added for the layerlisting. So it only counts layers in the group and doesn't count subgroups or layers in them. I think there was some issue that needs to be figured out for free text filter and how the layer counter works with it. Outside that it should be fairly easy fix.

**Comment by ZakarFin** [comment]
PRs are always nice :) Here's some related code:
- layer count/group: https://github.com/oskariorg/oskari-frontend/blob/2.6.0/bundles/framework/layerlist/view/LayerViewTabs/LayerList/LayerCollapse/LayerCollapsePanel.jsx#L145
- Display of count/unfiltered: https://github.com/oskariorg/oskari-frontend/blob/2.6.0/bundles/framework/layerlist/view/LayerViewTabs/LayerList/LayerCollapse/LayerCollapsePanel.jsx#L34-L36

Both the unfiltered count and filtered count should be updated to take subgroups into account. Might need to add some helper for groups to recurse through the structure to get the combined values.

**Comment by ZakarFin** [comment]
Fixed in the linked PR. The fix will be included in the next (2.7) release.
