### ISSUE TITLE
MIF/MID can't handle empty string on number/boolean columns

### ISSUE THREAD

**Issue by jampukka** [oskariorg/oskari-docs#271]
Instead they throw `java.lang.NumberFormatException: For input string: ""`.
Fix should be simple, if string is empty return null

Feel free to assign this to me

**Comment by ZakarFin** [comment]
Thanks for reporting this! If you are willing to fix it you can just submit a PR for it :) Anyone considering contributing a fix can just comment here if there's fear multiple people will jump on to fix this at the same time.

**Comment by ZakarFin** [comment]
Fixed in linked PR. Fix will be included in the next (2.7) release.
