### ISSUE TITLE
Create time for objects identifies wrongly in Oskari map service

### ISSUE THREAD

**Issue by Sanni975** [oskariorg/oskari-docs#279]
Hi, there is an issue in Oskari map service regarding the creation time for marked objects. For example, the user has several marked objects (like points) saved to a personal layer. The user wants to order the points based on the creation time of the objects. The Oskari map service identifies the creation time to number instead of date, because the order is wrong (picture in attachments). Would it be possible to rectify the column Creation time to be identified as a date?

**Comment by Sanni975** [comment]
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/113089302/189327222-b5c97e95-5db0-4998-a1e9-67f59630af76.png)

**Comment by Sanni975** [comment]
For example, in the list above the next object date should be 2.4.2020 not 1.6.2020

**Comment by ZakarFin** [comment]
I guess the erronous date order is not included in the picture, but should be an easy fix with a hopeful 2.9.0 inclusion.

**Comment by Sanni975** [comment]
That's great news! Do you have an estimate about when this 2.9.0 inclusion will be released?

**Comment by ZakarFin** [comment]
2.9.0 is due later this month. We are still working on some fixes that we want to include, but we are releasing it soon.

**Comment by ZakarFin** [comment]
Trying to solve this we realized that the screenshot is from the older "personaldata" bundle. The currently supported "drop-in replacement" for it is called "mydata". Can you try if using the current implementation solves the issue?

**Comment by Sanni975** [comment]
Good to know. I will be in touch with the user and open this issue again if these don't help. Thank you!

**Comment by Sanni975** [comment]
![Sieppaa2](https://user-images.githubusercontent.com/113089302/199191420-dcbbf402-118b-408b-9f93-ee6a82c16ca0.JPG)

**Comment by Sanni975** [comment]
Hi, I realised that this problem has not been solved since the dates still are organized wrongly. Do you have a solution for this? Earlier it was mentioned that there would be an update to this in September that would correct this problem?

**Comment by ZakarFin** [comment]
Hi, it all depends on the Oskari instance you are using. The updated code has been available for a while and you can see the latest in https://demo.oskari.org and https://kartta.paikkatietoikkuna.fi. If you can reproduce the issue on these instances I'm happy to take another look at it. But if it's on some other instance you should make sure they are using the "mydata" implementation for that `Omat Tiedot` listing and that the instance have been updated. The most recent version of Oskari is 2.9.1. You can check the Oskari-version by running `Oskari.VERSION` on the developer tools console of your browser.

**Comment by Sanni975** [comment]
Hi, our version is currently 2.7.2. I tried the demo oskari and wasn`t able to reproduce the issue. That would indicate that the 2.9.1 version should correct this bug. However, when creating sub-themes as far as possible (three navigations was the maximum under  the main theme), I was able to produce system error when trying to rename the third sub-theme in the demo.oskari.

**Comment by Sanni975** [comment]
Hi, our version is currently 2.7.2. I tried the demo oskari and wasn`t able to reproduce the issue. That would indicate that the 2.9.1 version should correct this bug. Thank you again for the quick reply.

**Comment by ZakarFin** [comment]
Thanks for testing this out :)
