### ISSUE TITLE
Print map of the specified area

### ISSUE THREAD

**Issue by ernoma** [oskariorg/oskari-docs#283]
I created issue #161 in year 2020 and it was closed (to my understanding) because at that time it was possible to easily get the print URL and also specify fractional resolution for the printing. Neither seem to be possible at least in the Oskari version in use at the city of Tampere currently (https://kartat.tampere.fi/oskari/).

**Comment by ZakarFin** [comment]
Have you tried if the scales configuration would do the trick https://oskari.org/api/bundles#/2.7.0/mapping/printout?

**Comment by ZakarFin** [comment]
We don't use it ourselves but according to the docs you can configure a scales array for printout and it should allow users to select the scale for the printout.

**Comment by jampukka** [comment]
Adding the optional configuration to the appsetups bundle config does work:

![image](https://user-images.githubusercontent.com/2799041/204845636-fa373c7b-9b3e-487a-ab20-9c53b1b0fa58.png)

The basic principle is that when a scale is selected from the list the map view is also zoomed to the selected scale. This doesn't always work as `AbstractMapModule#zoomToScale(scale, closest = false)` can't be guaranteed as the map module might only allow integer zoom levels (as is the case with Oskari OL MapModule by default).

Luckily the implementation has addressed this by including additional logic which should append the exact resolution to the GetPrintout request. However, upon further inspection it looks like the `if` clause [here](https://github.com/oskariorg/oskari-frontend/blob/2.9.1/bundles/framework/printout/view/BasicPrintout.js#L522) is never actually true. By looking at the code something like `find('input[name=printout-scale]:checked').val() === 'configured'` should work but I haven't had the time to test it yet.

In addition, the logic for creating preview printout requests is separate and [seems to](https://github.com/oskariorg/oskari-frontend/blob/2.9.1/bundles/framework/printout/view/BasicPrintout.js#L557) be missing this additional logic. If not added, the preview images and the actual pdf printouts will be in different resolution and thereby enclosing different bounding boxes which would be very misleading, so the logic should also be added there.

Here's the result if native resolutions / scale denominators are used (happens automatically when omitting the `scales` array from `config`) where you can see the scale denominators of the native resolutions of this appsetup are not even close to the ones specified in the first image:
![image](https://user-images.githubusercontent.com/2799041/204846555-0109d958-baea-4055-8e74-87e24b01971a.png)

**Comment by ernoma** [comment]
Thank you @ZakarFin and @jampukka!

I passed this information forward to GIS unit at the city of Tampere and hopefully they are able to configure more zoom levels available.

**Comment by ZakarFin** [comment]
Closing this as there doesn't seem to be actionable items or suggestions here for making any improvements on the code and this is now linked to another issue that involves printing.
