### ISSUE TITLE
Sub-theme bug in Oskari mapservice

### ISSUE THREAD

**Issue by Sanni975** [oskariorg/oskari-docs#284]
Hi, our user in Tampere city encountered a bug when renaming sub-themes in Oskari mapservice. The issue was as follows: When renaming subthemes, the newly updated subthemes jump as a main theme (see attachment image). The user managed to fix the problem by creating entirely new sub-themes under correct main theme and transferred all of the maplayers back to correct subtheme. Can this bug be corrected so that when renaming subthemes, it would not change the location of the subthemes into main category?
![image001](https://user-images.githubusercontent.com/113089302/199198180-402757db-d50b-4975-988e-e0468e80d399.png)

**Comment by ZakarFin** [comment]
What is the Oskari version you have encountered this in and can you reproduce it on https://demo.oskari.org?

**Comment by Sanni975** [comment]
Hi, our version is currently 2.7.2. I tried the demo oskari and wasn`t able to reproduce the issue. That would indicate that the 2.9.1 version should correct this bug. However, when creating sub-themes as far as possible (three navigations was the maximum under the main theme), I was able to produce system error when trying to rename the third sub-theme in the demo.oskari.
