### ISSUE TITLE
Metadata boundaries which cross the International Date Line are shown wrong

### ISSUE THREAD

**Issue by Miselius** [oskariorg/oskari-docs#4]
AH-3635

In the Arctic SDI Geoportal:
1.When searching Metadata with the string "arctic"
2. Multiple results are found, for which the boundaries cross the International Date Line.
3. These boundaries are shown wrong (possibly OpenLayers problem).

Possible fixes:
- http://gis.stackexchange.com/questions/7064/the-international-date-line-wrap-around
- http://gis.stackexchange.com/questions/83425/splitting-linestrings-on-the-dateline-with-openlayers/83772#83772

**Comment by ZakarFin** [comment]
Fixed in oskariorg/oskari-server#104
