### ISSUE TITLE
Size error on download of jetty-oskari-bundle

### ISSUE THREAD

**Issue by pjduplooy** [oskariorg/oskari-docs#42]
Hi guys

I have been trying in vain to download the jetty bundle from the Oskari home.  I get a size mismatch about halfway through the download.  

I have tried Firefox with DownthemAll, as well as without, and have also tried IE.

Any help on this will be greatly appreciated.

Pieter

**Comment by ZakarFin** [comment]
Hmm, I just created a new version like 10 minutes ago. Unfortunately this replaces the old one which probably confuses any download that's in progress at the time. Could this be the reason? Could you try again now?

**Comment by pjduplooy** [comment]
Will try again.  But this happened yesterday.

**Comment by ZakarFin** [comment]
Just downloaded it successfully with Chrome (but using the internal network so that might not be a good test case) and from a server (that's not on the same local network) with "wget http://oskari.org/build/server/jetty-8.1.16-oskari.zip" which is a better test case since the network should be the same as anyone downloading from the internet, but again it's not exactly the same as a browser download.

**Comment by pjduplooy** [comment]
Hi , I have just downloaded, and it still gives me a size mismatch,.

Will try Chrome, as well as wget

**Comment by pjduplooy** [comment]
Hi

Failing with wget as well.  Havent tried chrome.

Here is the error:

jetty-8.1.16-oskari.zip        23%[==========>                                       ] 101.08M   122KB/s    in 10m 1s

2017-03-17 12:54:47 (172 KB/s) - Connection closed at byte 105992811. Retrying.

**Comment by pjduplooy** [comment]
Hi I have just tried again with Chrome, and wget, and download still fails.  Is it possible to provide it from another repository?

Regards
Pieter

**Comment by ZakarFin** [comment]
Weird. I uploaded the zip to dropbox. Can you test if you can download it from there: https://www.dropbox.com/s/2qu5f1z5pcjc2rg/jetty-8.1.16-oskari_1.41.2.zip?dl=0

I'll remove the file in the future and it won't be updated, but just to test it out.

**Comment by pjduplooy** [comment]
Thanks for the dropbox link, I was able to download from there.

Regards

Pieter
