### ISSUE TITLE
Jetty Bundle analysis tool - Buffer problem

### ISSUE THREAD

**Issue by Dranu** [oskariorg/oskari-docs#49]
Hello!

Today I tried to see how well the analysis (beta) version works with the prebuilt Jetty Bundle. At http://www.paikkatietoikkuna.fi/web/fi/kartta it works like it should but with the premade Jetty I had a critical issue with the buffer tool (same happens with http://demo.oskari.org/).

Issue: I create a line and try to add 1 meter buffer to it with the analysis tool. For some reason, the buffer turns out to be huge ( 50-100km). I'm guessing somewhere in the source code, the buffer has a wrong multiplier.

**Comment by ZakarFin** [comment]
Hi, thanks for reporting this! My guess is that the functionality doesn't work too well with projections using degrees. It has been developed using metric projection.

**Comment by Dranu** [comment]
Thanks for the quick reply. Took me quite a long time to get back to the problem and it also took time to properly change the projection from 4236 to 3857. You were right, the problem was with the degrees and using a metric projection the problem was solved. Thanks again!
