### ISSUE TITLE
Search field for admin bundles

### ISSUE THREAD

**Issue by gismaka** [oskariorg/oskari-docs#5]
I suggest, could add "search field" for A:MAP LAYER and LAYER RIGHTS. Lists are so longs and it is very difficult find right layer. CTRL+F is not user friendly.

**Comment by ZakarFin** [comment]
Personally I would prefer integrating admin functionality regarding layers to the existing layer selector and remove the duplicate code/functionality that we now have. The existing layerselector already has search and other types of filtering implemented. As a user you shouldn't need to use different layer listings in different places based on what you want to do with a layer. This would require the layerselector to allow admin functionality to inject itself to the UI, but it's something that other functionalities in Oskari already do so nothing new there.

**Comment by gismaka** [comment]
Sounds like a plan!

**Comment by ZakarFin** [comment]
Implementation for this is included in #61
