### ISSUE TITLE
"Analysis Layer Union" -analysis shows "Buffers and sectors"

### ISSUE THREAD

**Issue by Dranu** [oskariorg/oskari-docs#51]
As title says, when choosing the analysis "Analysis Layer Union", Oskari (and demo) shows the options for "Buffers and sectors" rather than the correct one.

**Comment by ZakarFin** [comment]
Hi, thanks for reporting this! Seems to do so on the english language version while the finnish one works correctly.

**Comment by ZakarFin** [comment]
Just merged the fix to develop branch so this will be fixed in the next release.
