### ISSUE TITLE
My Places - problems with changing / editing location

### ISSUE THREAD

**Issue by SannaJokela** [oskariorg/oskari-docs#56]
Problems changing point location in My Data functionality: it should take the scale in which the point has been added into account, now the edit option zooms "too close" and you can not change the location easily (e.g. you are adding points in European level, but you put accidentaly your point into Finland and it should be in Sweden ==> and this results to the fact that you have to zoom out quite a bit and drag the point where you want it). 

Also you have to remember to push the Save-button in the attribute dialog (which also gets in the way of the point so you easily shut down the dialog). 

When testing changing location with ELF-map service, the saving does not seem to work at all. 

Also when editing the point, there is no "refresh"-button and My Data Layer does not show unless you refresh the whole map service and retrieve your layer again from the Map Layers list.

**Comment by ZakarFin** [comment]
Are you talking about editing my places features? New my places layer should show up in the list and any added, removed or modified places should be updated on the map when the item is saved (user clicks save-button). There's no need for a refresh-button. Another problem is that the feature details form is opened on the map which might cover the geometry that the user might want to edit. In my opinion the form should not be attached to the map, but a floating popup or something like that.

**Comment by ZakarFin** [comment]
Also what do you mean taking scale into account? You should be able to zoomout while editing as normal. Are you saying that when clicking the edit-link on a my places feature you are automatically zoomed in "too close"? If so, do you have any suggestions on what could be the right amount of zoom?

**Comment by SannaJokela** [comment]
Yes, sorry My places. When you edit and save one feature, all the other features "dissappear" and you can see only the edited feature. I think this just happened with ELF portal (it was acting a bit slow also). 

Now when testing with Paikkatietoikkuna, the other features stay visible also. BUT, now when I try to change the location and drag the point into new place and (because the info-pop-up is on the way I had to shut it down) and have not saved the point yet, I would assume the edits are not saved. When I go back to edit it, it zooms into the location I just try to drag the point but it does not show the point. When I refresh the map, the point is in its original position.

The scale issue: it would be reasonable that the zoomlevel where the point is added would be saved with the feature and later if edit it again, it would choose the same zoomlevel. Or would let the user to decide weather to zoom to the feature or not.

**Comment by ZakarFin** [comment]
Ok, the only way to "commit" the changes is clicking the save-button which is not available if you close the infobox :) The close-icon should do the same as pressing the cancel-button and remove the option to edit the geometry, but based on your description this is not the case.

Saving the information about zoom-level of the map when a feature is added/modified can be moved to another issue. Could be a nice-to-have feature.

**Comment by ZakarFin** [comment]
Oskari version 2.1.0 has a new edit form for my places that is no longer "tied" to the map coordinates and is freely draggable and doesn't "block" user from editing the geometry. I think this was the issue here but anyway there hasn't been much life around this issue so closing it.
