### ISSUE TITLE
My Places & ol4 issue

### ISSUE THREAD

**Issue by Dranu** [oskariorg/oskari-docs#71]
Hello,

I read that you had updated to using ol4 instead of ol2. However, there's a slight problem with it.
When trying to draw a place on the map, the following error comes up (on Chrome console):

"ol-v4.4.2-oskari.js:39 Uncaught TypeError: Cannot read property '0' of undefined
    at Fb (ol-v4.4.2-oskari.js:39)
    at Eb.Ww (ol-v4.4.2-oskari.js:35)
    at e.getPolygonArea (DrawPlugin.ol3.js:721)
    at DrawPlugin.ol3.js:699
    at Array.forEach (<anonymous>)
    at e.sumMeasurements (DrawPlugin.ol3.js:696)
    at e.getFeaturesAsGeoJSON (DrawPlugin.ol3.js:593)
    at e.sendDrawingEvent (DrawPlugin.ol3.js:509)
    at Is.<anonymous> (DrawPlugin.ol3.js:915)
    at Is.b (ol-v4.4.2-oskari.js:52)"

This happens with the regular Jetty Bundle, with updated server / frontend and with demo.oskari.org using default EPSG:4326 projection (haven't tried with another).

Additionally, when I draw a line and save it, the location for the line changes drastically (probably an issue with the projection when saving to database).

Best regards
Jiri

**Comment by jampukka** [comment]
Thanks for reporting the issue, we'll look into it. This definitely should not be happening.

**Comment by Dranu** [comment]
A small update: Tested doing a line close to origin point and turns out, the shape is rotated 90 degrees counter clockwise (Drew a  "--|" -shape and it turned to "T" ).

**Comment by jampukka** [comment]
And the location also changed drastically? Sounds like an axis order issue.

**Comment by Dranu** [comment]
Yes, when I drew something on top of Helsinki, the shape moved to slightly off the coast of southern Iran when it was saved to database.

**Comment by jampukka** [comment]
Thanks, we have pretty clear vision on why this happens. It _should_ have already been fixed but we will have to double check it.

In addition to the line showing up in the wrong place, drawing a Point Feature fails altogether, correct?

**Comment by Dranu** [comment]
Yes the error I pasted in the first message came from trying to draw a point (not marker).

**Comment by ZakarFin** [comment]
This has been fixed on the develop branch so the fix will be part of the 1.48.0 release (later this week or the next one).
