### ISSUE TITLE
Oskari & CKAN compatibility

### ISSUE THREAD

**Issue by SannaJokela** [oskariorg/oskari-docs#73]
Testing is needed regarding CKAN based metadata interface and Oskari. This issue has been discussed in Trello https://trello.com/c/7b5bDrWo/126-ckan-oskari-needs-more-information and Oskari mailing list https://lists.osgeo.org/pipermail/oskari-user/2018-September/000089.html. More information about this issue is needed. 

How CKAN metadatainfo can be used in Oskari? Does CKAN provide OGC compatible CSW? Needs testing.

Steps:
1. Test link/interface from CKAN metadata service (coming up from Lounaistieto-service)
2. Checking how the metadata reader in Oskari takes in CKANS CSW data
3. Improving / parcing the metadata tool in Oskari
4. Possible other needs in CKAN side - INSPIRE-compatibility?

Needs: 
-test data/interface from CKAN providing CSW
-Oskari instance for testing

Dependencies: 
http://oskari.org/api/bundles#unreleased/mapping/metadatacatalogue
http://docs.ckan.org/projects/ckanext-spatial/en/latest/csw.html

**Comment by SannaJokela** [comment]
We have gone through this issue a bit with Natalia Räikkönen from Lounaistieto and we figured out that CKAN does not provide suitable metadata format in CSW (although it seems to have an extension available https://docs.ckan.org/projects/ckanext-spatial/en/release-v1.8/#csw-server. 

There is a possibility to integrate CKAN-Oskari and this can be done by creating a parser for Oskari to read json format in CKAN (this was discussed in Gitter). Here are the formats CKAN provides the metadata :https://ckan.org/open-standards/. 

And here is an example metadata from CKAN: https://data.lounaistieto.fi/data/api/action/package_show?id=varsinais-suomen-vaihemaakuntakaava 

This issue requires a project where this issue is further tested.

**Comment by ZakarFin** [comment]
Closing since there haven't been activity regarding this.
