### ISSUE TITLE
Drawtools box drawing draws triangle when modifyControl is setted to true

### ISSUE THREAD

**Issue by kuosman** [oskariorg/oskari-docs#79]
Try:
- go to : http://oskari.org/examples/rpc-api/rpc_example.html
- run following code:
```
var data = ['my functionality id', 'Box', {allowMultipleDrawing:false, modifyControl:false}];
channel.postRequest('DrawTools.StartDrawingRequest', data);
```
- draw box
- when drawing finished then showing triangle and event returns geojson where is four coordinates, first and latest has same coordinates
- if i change modifyControl to true, looks right and there is five coordinates

**Comment by ZakarFin** [comment]
Fixed in develop branch
