### ISSUE TITLE
Delete users

### ISSUE THREAD

**Issue by petrilinna** [oskariorg/oskari-docs#80]
I can't delete any users in the Oskari UI. I have done new admin user but I can't delete original admin user but not else other users what I have done. Same problems when I logged in original admin user. The problem
![deleteuser](https://user-images.githubusercontent.com/44966913/48340423-4353e800-e673-11e8-8277-cd92d2624d4a.png)
 window appears "Deleting user data failed in service: analysis".
Best regards, Petri Linna, petri.linna@tut.fi, work: +358 408262720

**Comment by ZakarFin** [comment]
Thanks for reporting this.

**Comment by ZakarFin** [comment]
Looks like doing this on a fresh install works ok. Maybe there's something wrong on the database tables? Would need to have a look at some server logs to see what's going on.

**Comment by petrilinna** [comment]
Here is the log, when we tried to delete user.

T. Petri L.

**Comment by ZakarFin** [comment]
This was due to database not having all the tables. Initialization of the database had failed as the postgis-extension wasn't activated for the database Oskari tried to initialize.
