### ISSUE TITLE
Oskari.org website development scheme

### ISSUE THREAD

**Issue by SannaJokela** [oskariorg/oskari-docs#82]
Oskari.org website is to be revised in 2019-2020. The community.oskari.org pages will be merged with Oskari.org creating a possibility to see updates on community projects and other Oskari news. Oskari JDF is responsible for the layout design. 

[Planning document, in Finnish.](https://docs.google.com/document/d/19kDa6lxhGEsoLHFmEXvRa1ly2rPSUyxofFirHD3Cqhg/edit#)

**15.06.2020**: Only front page missing, all other things migrated, some blog posts need to be revised. Changed articles and pages from the old community pages into "sketch" so they won't be visible anymore. The old community pages can be active for two months and then they can be shut down.
**11.05.2020**: Community & Gallery pages are available
**29.10.2019**: Most of the relevant articles from verkosto.oskari.org have been added to GitHub. 

## New:
[Community -pages](https://oskari.org/community/oskari_community)
- Needs to be linked through front pages

[Gallery](https://oskari.org/gallery)
-[Remember to add images in public/images/gallery](https://github.com/oskariorg/oskari-docs/tree/master/community/gallery)

[Developer blog](https://oskariorg.github.io/)
- Do we need a different name?
- Blog about Hierachical layer list needs to be done
- Blog about Download bundle needs to be done
- Blog about why choose Oskari needs to be done

[About](https://www.oskari.org/about) 

## Under construction:

- First page layout ==> different user groups
- Integration of "Guide" and "Documentation" ==> some of the content from Guide to the home page

## Pages that need revision
- [Features](https://oskari.org/documentation/features)
- [Architecture](https://oskari.org/documentation/architecture_basics)

**Comment by ZakarFin** [comment]
Approved on 8.1. PSC-meeting.

**Comment by SannaJokela** [comment]
This needs a new front page design and new graphical instructions (due to Mr Oskari Otter) :) - Does somebody have time to do this next year?

Also updated the issue description with links to example pages.

**Comment by SannaJokela** [comment]
Edited the description, most of the work is done. Front page needs work (mockup has been updated)+ some older blog posts need to reviewed (I will do this).

**Comment by SannaJokela** [comment]
Added some pages that need revision.

**Comment by SannaJokela** [comment]
Updated the current situation, still need the front page so the community section can be found :) Also FAQ is not yet linked from anywhere, I think. Also I added the articles and pages in the community pages to "sketch" status, so they are not visible and added there information and request to follow only oskari.org

**Comment by ZakarFin** [comment]
I think is mostly done but we still really need to update features page (perhaps with a similar system as gallery uses and linking the actual code/bundles that relates to features) and the architecture page. I just removed references to bunch of pages talking about the transport webapp that was replaced with code on oskari-server a year ago or so.

**Comment by ZakarFin** [comment]
Current status: restructuring the documentation (and visual improvements) is currently worked on by the communications coordinator.

**Comment by ZakarFin** [comment]
A few moments later:  we are building the new site on: https://github.com/oskariorg/oskari-documentation-site with the "more technical content" being versioned in https://github.com/oskariorg/oskari-documentation. It's not ready to be launched and we might need to launch the new one side-by-side with the old one until we can migrate the documentation to the new site.
