### ISSUE TITLE
Support for Bing and OpenStreetMap data

### ISSUE THREAD

**Issue by haflidi** [oskariorg/oskari-docs#95]
It would be great to be able to add OpenStreetMap datalayers and Bing basemap to OSKARI.
Both of these data sources have supported functions in OpenLayers.

**Comment by ZakarFin** [comment]
There's some API key functionality for Bing maps on OpenLayers, but I don't know if it's required. Should check what the usage terms says on the service says. Do you mean that the admin should be able to add a new layer of type "Bing maps" and the admin UI would ask for the API key or something like that?

I don't think the default OSM source in Openlayers is viable for Oskari geoportals: https://operations.osmfoundation.org/policies/tiles/. The example app in Oskari (http://dev.oskari.org) uses OSM data as vector tiles from https://cloud.maptiler.com/  for the default "base map". You can also setup a service yourself that provides OSM data and register it to Oskari. Or if you know of a service that's free with ~unlimited usage we could definitely add it as demo content for Oskari.

It's a bit iffy how these could be used in Oskari. On one hand it would be kinda nice to have more stuff available after "unboxing" the software but then we really should notify the service administrator of the  usage terms and limitations of such services.

**Comment by haflidi** [comment]
I looked at the demo, its. good.

But Bing is not difficult to use in Openlayers. You use
            source : new ol.source.BingMaps(options),
and options is similar to: "{key:'Ailr78fw8dV1xx85-nR369lo7cYGHegdfxkBWIGhU,Q9vUG P123uB5jQWEb8eze',imagerySet:'Aerial'}", n.b. key has a fake value here :)
I assume that the user registering the BingMap basemap in OSKARI would need to go to the Bing website first to generate the key.

**Comment by ZakarFin** [comment]
Sure :) I'm not saying it's technically difficult, but just wondering where it fits and what's the requirement. And looks like we are on the same page with having it as a new type of layer for the admin to add.

**Comment by haflidi** [comment]
Yes, right, I agree it should be a new type of layer.

**Comment by ZakarFin** [comment]
I guess this could include Here maps as well https://openlayers.org/en/latest/examples/here-maps.html with the same thing that the admin just needs to provide an api key.

**Comment by ZakarFin** [comment]
Implemented in oskariorg/oskari-frontend#792, oskariorg/oskari-frontend#800. Will be included in 1.51.0
